### ISSUE TITLE
Crash when tags load

### ISSUE THREAD

**Issue by Evanineo** [KampWskiR/Level-Tags#2]
My game crashed when I searched for the most liked levels to see if there were any new features with tags. My game didn't crash when I looked at some other random levels that didn't have any tags, though. FYI, the mods I'm using are BetterInfo, BetterInputs, Clean Startpos, Colorful Icons, Custom Keybinds, Editor Level ID API, EditorTab API, EvenMoreLevelTags, Functional, Globed, Level Tags (of course), Misc Bugfixes, Node IDs, Object Workshop, SkipEditorObjects, Unlisted Objects in Editor, and some outdated mods.

**Comment by KampWskiR** [comment]
Idk how to explain this issue, but the mod was crashing for people who didn't have the texture loader mod.
This should be fixed in patch v0.2.1-alpha.
