### ISSUE TITLE
Tag suggestions

### ISSUE THREAD

**Issue by FRBFStudios** [KampWskiR/Level-Tags#3]
This mod is great, but a "Shitty", "Holiday", "2.0", "Legacy Physics" (maybe make that one apply automatically) and "Hard Coins" tag would be awesome to have :)

**Comment by KampWskiR** [comment]
may be wrong but I dont think geode allows mods to use words like "shitty", for the rest i think we could add these.
For tags suggestions I would prefer if you used our discord for that. https://discord.gg/6GXYHf9WTB

**Comment by KampWskiR** [comment]
btw we were thinking about "automatic tags" but it would absolutely break the tag search we are working on
